[tool.poetry]
name = "olas-operate-app"
version = "0.2.0-rc292"
description = ""
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>"]
readme = "README.md"
packages = []
include = []

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-middleware.git", rev = "af8cf57aa9aa021cad17c522dedb29a6aef8d025"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
